# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7a47048a98c00ffbd8275d8d0982ffb797a694c6a406e58053abd41f0606a90636c54bb44564b8fbcca098ce46156a5f558c3c4135af19060c45ad5648e6142

test:
  secret_key_base: 8fe763742b24d6b634600e3c0dc4ad1ced53b6cedb86fd193c46909ddd454ce88cb0977acf96a85e573f89b65db0d26db8bf03a1808803a05efbdeba9afe6ad0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
